<?php
session_start();
if (!isset($_SESSION["user_id"])) {
    header("Location: login.php");
    exit;
}

include "auth/dhc.php";

/* =========================
   DASHBOARD STATISTICS (SAFE)
========================= */
$totalLoaned = 0;
$totalCollected = 0;

/* Total Loaned */
$res = $conn->query("SELECT SUM(amount) AS total FROM loans");
if ($res) {
    $row = $res->fetch_assoc();
    $totalLoaned = $row['total'] ?? 0;
}

/* Total Collected */
$res = $conn->query("SELECT SUM(amount) AS total FROM payments");
if ($res) {
    $row = $res->fetch_assoc();
    $totalCollected = $row['total'] ?? 0;
}

$outstanding = $totalLoaned - $totalCollected;
$collectionRate = ($totalLoaned > 0)
    ? round(($totalCollected / $totalLoaned) * 100, 1)
    : 0;

/* =========================
   CHART DATA
========================= */
/* Loans by Status */
$activeLoans = 0;
$completedLoans = 0;

$res = $conn->query("SELECT status, COUNT(*) total FROM loans GROUP BY status");
if ($res) {
    while ($r = $res->fetch_assoc()) {
        if ($r['status'] === 'active') $activeLoans = $r['total'];
        if ($r['status'] === 'completed') $completedLoans = $r['total'];
    }
}

/* Monthly Collections */
$months = [];
$monthlyAmounts = [];

$res = $conn->query("
    SELECT DATE_FORMAT(payment_date, '%b') AS month,
           SUM(amount) total
    FROM payments
    GROUP BY MONTH(payment_date)
    ORDER BY MONTH(payment_date)
");
if ($res) {
    while ($r = $res->fetch_assoc()) {
        $months[] = $r['month'];
        $monthlyAmounts[] = $r['total'];
    }
}

/* =========================
   FETCH REPORTS
========================= */
$reports = $conn->query("
    SELECT r.report_id,
           r.report_type,
           CONCAT(u.fname,' ',u.lname) AS generated_by_name,
           r.description,
           r.generated_at
    FROM reports r
    JOIN users u ON r.generated_by = u.user_id
    ORDER BY r.generated_at DESC
");
?>

<?php include "includes/header.php"; ?>

<body class="layout-fixed sidebar-expand-lg sidebar-open bg-body-tertiary">
<div class="app-wrapper">
<!-- Header -->
  <nav class="app-header navbar navbar-expand bg-body">
    <div class="container-fluid">
      <ul class="navbar-nav">
        <li class="nav-item">
          <a class="nav-link" data-lte-toggle="sidebar" href="#">
            <i class="bi bi-list"></i>
          </a>
        </li>
        <li class="nav-item d-none d-md-block"><a href="#" class="nav-link">Home</a></li>
        <li class="nav-item d-none d-md-block"><a href="#" class="nav-link">Contact</a></li>
      </ul>

      <ul class="navbar-nav ms-auto">
        <?php include "includes/navbar.php"; ?>
        <?php include "includes/navbar.links.php"; ?>
      </ul>
    </div>
  </nav>

<?php include "includes/sidebar.php"; ?>

<main class="app-main">
<div class="container-fluid py-4">

<h2 class="fw-bold">Reports</h2>
<p class="text-muted">Financial overview and analytics</p>

<!-- ================= SUMMARY CARDS ================= -->
<div class="row g-4 mb-4">

    <div class="col-md-3">
        <div class="card shadow-sm p-4 text-center">
            <p class="text-muted mb-1">Total Loaned</p>
            <h3 class="fw-bold">$<?= number_format($totalLoaned) ?></h3>
        </div>
    </div>

    <div class="col-md-3">
        <div class="card shadow-sm p-4 text-center">
            <p class="text-muted mb-1">Total Collected</p>
            <h3 class="fw-bold text-success">$<?= number_format($totalCollected) ?></h3>
        </div>
    </div>

    <div class="col-md-3">
        <div class="card shadow-sm p-4 text-center">
            <p class="text-muted mb-1">Outstanding</p>
            <h3 class="fw-bold text-warning">$<?= number_format($outstanding) ?></h3>
        </div>
    </div>

    <div class="col-md-3">
        <div class="card shadow-sm p-4 text-center">
            <p class="text-muted mb-1">Collection Rate</p>
            <h3 class="fw-bold"><?= $collectionRate ?>%</h3>
        </div>
    </div>

</div>

<!-- ================= CHARTS ================= -->
<div class="row g-4 mb-4">

    <div class="col-md-6">
        <div class="card shadow-sm p-4">
            <h5 class="fw-bold mb-3">Loans by Status</h5>
            <canvas id="loanStatusChart"></canvas>
        </div>
    </div>

    <div class="col-md-6">
        <div class="card shadow-sm p-4">
            <h5 class="fw-bold mb-3">Monthly Collections</h5>
            <canvas id="monthlyChart"></canvas>
        </div>
    </div>

</div>

<!-- ================= REPORTS TABLE ================= -->
<!-- <div class="card shadow-sm">
<div class="card-body">

<h5 class="fw-bold mb-3">Generated Reports</h5>

<table class="table table-hover align-middle">
<thead class="table-light">
<tr>
    <th>ID</th>
    <th>Type</th>
    <th>Generated By</th>
    <th>Description</th>
    <th>Date</th>
</tr>
</thead>
<tbody> -->

<?php if ($reports && $reports->num_rows > 0): ?>
<?php while ($row = $reports->fetch_assoc()): ?>
<tr>
    <td><?= $row['report_id'] ?></td>
    <td class="text-capitalize"><?= htmlspecialchars($row['report_type']) ?></td>
    <td><?= htmlspecialchars($row['generated_by_name']) ?></td>
    <td><?= htmlspecialchars($row['description']) ?></td>
    <td><?= date("d M Y", strtotime($row['generated_at'])) ?></td>
</tr>
<?php endwhile; ?>
<?php else: ?>
<tr>
    <td colspan="5" class="text-center text-muted">No reports available</td>
</tr>
<?php endif; ?>

</tbody>
</table>

</div>
</div>

</div>
</main>

</div>

<?php include "includes/script-links.php"; ?>

<!-- ================= CHART.JS ================= -->
<script src="https://cdn.jsdelivr.net/npm/chart.js"></script>
<script>
/* Pie Chart */
new Chart(document.getElementById('loanStatusChart'), {
    type: 'pie',
    data: {
        labels: ['Active', 'Completed'],
        datasets: [{
            data: [<?= $activeLoans ?>, <?= $completedLoans ?>],
            backgroundColor: ['#198754', '#0d6efd']
        }]
    }
});

/* Bar Chart */
new Chart(document.getElementById('monthlyChart'), {
    type: 'bar',
    data: {
        labels: <?= json_encode($months) ?>,
        datasets: [{
            label: 'Amount Collected',
            data: <?= json_encode($monthlyAmounts) ?>,
            backgroundColor: '#0d6efd'
        }]
    },
    options: {
        scales: {
            y: { beginAtZero: true }
        }
    }
});

</script>

</body>
</html>
